# Generated by Django 4.0.1 on 2022-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0002_pricingmodel_userpricingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='scan_limit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpricingmodel',
            name='scan_count',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
