# Generated by Django 4.0.1 on 2022-01-23 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0003_pricingmodel_scan_limit_userpricingmodel_scan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpricingmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
