# Generated by Django 4.0.1 on 2022-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0004_alter_userpricingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='days',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpricingmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
